### ISSUE TITLE
HU01 - Consultar catálogo de álbumes

### ISSUE THREAD

**Issue by diegonaranjo94** [OrangeScript/proyecto_misw4203#1]
Como usuario visitante quiero navegar el catálogo de los álbumes para escoger los que más me interesan

**Comment by OrangeScript** [comment]
Como usuario visitante quiero navegar el catálogo de los álbumes para escoger los que más me interesan

**Comment by diegonaranjo94** [comment]
**Tareas HU01**

> - [ ] Crear componente de álbum
> - [ ] Desarrollo maquetado listado albumes
> - [ ] Desarrollo estilos listado albumes
> - [ ] Conexión a la API REST de álbumes
> - [ ] Creación de routing para este componente
> - [ ] Pruebas unitarias
> - [ ] Pruebas de e2e
> - [ ] Pruebas de API consultar catálogo de álbumes (pruebas de integración)
