### ISSUE TITLE
HU04 - Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by jscalderonb12** [OrangeScript/proyecto_misw4203#3]
Como usuario visitante quiero ver el detalle de un artista para ampliar la información sobre el.

**Comment by diegonaranjo94** [comment]
**Tareas HU04**

> - [ ] Crear componente detalle de artista
> - [ ] Desarrollo maquetado detalle de artista
> - [ ] Desarrollo estilos detalle de artista
> - [ ] Conexión a la API REST de detalle de artista
> - [ ] Creación de routing para este componente
> - [ ] Pruebas unitarias
> - [ ] Pruebas de e2e
> - [ ] Pruebas de API consultar catálogo de álbumes (pruebas de integración)
