### ISSUE TITLE
HU05 - Consultar listado de colecciones

### ISSUE THREAD

**Issue by jscalderonb12** [OrangeScript/proyecto_misw4203#4]
Como usuario visitante quiero consultar el listado de coleccionistas para seleccionar el que más me interese.

**Comment by diegonaranjo94** [comment]
**Tareas HU05**

> - [ ] Crear componente para listar colecciones
> - [ ] Desarrollo maquetado de listado de colecciones
> - [ ] Desarrollo estilos de listado de colecciones
> - [ ] Conexión a la API REST de listado de colecciones
> - [ ] Creación de routing para este componente
> - [ ] Pruebas unitarias
> - [ ] Pruebas de e2e
> - [ ] Pruebas de API consultar catálogo de álbumes (pruebas de integración)
