### ISSUE TITLE
HU06 - Consultar la información detallada de coleccionista

### ISSUE THREAD

**Issue by jscalderonb12** [OrangeScript/proyecto_misw4203#6]
Como usuario visitante quiero ver el detalle de un coleccionista para conocer sus gustos musicales.

**Comment by diegonaranjo94** [comment]
**Tareas HU06**

> - [ ] Crear componente para ver detalle de coleccionista
> - [ ] Desarrollo maquetado de detalle de coleccionista
> - [ ] Desarrollo estilos de detalle de coleccionista
> - [ ] Conexión a la API REST de detalle de coleccionista
> - [ ] Creación de routing para este componente
> - [ ] Pruebas unitarias
> - [ ] Pruebas de e2e
> - [ ] Pruebas de API consultar catálogo de álbumes (pruebas de integración)
