### ISSUE TITLE
HU07 - Crear álbum

### ISSUE THREAD

**Issue by jscalderonb12** [OrangeScript/proyecto_misw4203#7]
Como coleccionista quiero agregar un álbum al listado.

**Comment by diegonaranjo94** [comment]
**Tareas HU07**

> - [ ] Crear componente para crear álbum
> - [ ] Definir formulario para crear àlbum
> - [ ] Desarrollo maquetado de crear álbum
> - [ ] Desarrollo estilos de crear álbum
> - [ ] Conexión a la API REST de crear álbum
> - [ ] Creación de routing para este componente
> - [ ] Pruebas unitarias
> - [ ] Pruebas de e2e
> - [ ] Pruebas de API consultar catálogo de álbumes (pruebas de integración)
