### ISSUE TITLE
HU08 - Asociar tracks con un álbum

### ISSUE THREAD

**Issue by jscalderonb12** [OrangeScript/proyecto_misw4203#8]
Como coleccionista quiero agregar tracks a un álbum para actualizar el catálogo.

**Comment by diegonaranjo94** [comment]
**Tareas HU08**

> - [ ] Crear componente para asociar tracks con un álbum 
> - [ ] Definir formulario para asociar tracks con un álbum
> - [ ] Desarrollo maquetado de asociar tracks con un álbum
> - [ ] Desarrollo estilos de asociar tracks con un álbum
> - [ ] Conexión a la API REST de asociar tracks con un álbum
> - [ ] Creación de routing para este componente
> - [ ] Pruebas unitarias
> - [ ] Pruebas de e2e
> - [ ] Pruebas de API consultar catálogo de álbumes (pruebas de integración)
